# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Shared settings are here. Target overrides are in versions/*/gradle.properties.
mod.id=syrup_essentials
mod.name=Syrup Essentials
mod.group=net.syrupstudios
mod.version=0.4.0
mod.description=Syrup Studio's Essentials Mod adding commands for players and server operators
mod.authors=SodaSyrup
mod.license=RSL-1.0
deps.lombok=1.18.38
