modLoader="javafml"
loaderVersion="[${forge},)"
license="${license}"
mixinConfigs="syrup-essentials.mixins.json"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
authors="${authors}"
description='''${modDescription}'''

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="[${mc}]"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="syrup_library"
mandatory=true
versionRange="[${syrupLibraryVersion},)"
ordering="AFTER"
side="BOTH"
