modLoader="javafml"
loaderVersion="[${forge},)"
license="${license}"
mixinConfigs="syrup-essentials.mixins.json"

[[mods]]
modId="syrup_essentials"
version="${version}"
displayName="${modName}"
authors="${authors}"
description='''${modDescription}'''

[[dependencies.syrup_essentials]]
modId="minecraft"
mandatory=true
versionRange="[${mc}]"
ordering="NONE"
side="BOTH"

[[dependencies.syrup_essentials]]
modId="syrup_library"
mandatory=true
versionRange="[0.3.0,)"
ordering="AFTER"
side="BOTH"
