modLoader="javafml"
loaderVersion="[1,)"
license="${license}"

[[mods]]
modId="syrup_essentials"
version="${version}"
displayName="${modName}"
authors="${authors}"
description='''${modDescription}'''

[[mixins]]
config="syrup-essentials.mixins.json"

[[dependencies.syrup_essentials]]
modId="minecraft"
type="required"
versionRange="[${mc}]"
ordering="NONE"
side="BOTH"

[[dependencies.syrup_essentials]]
modId="syrup_library"
type="required"
versionRange="[0.3.0,)"
ordering="AFTER"
side="BOTH"
