modLoader="javafml"
loaderVersion="[1,)"
license="${license}"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
authors="${authors}"
description='''${modDescription}'''

[[mixins]]
config="syrup-essentials.mixins.json"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="[${mc}]"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="syrup_library"
type="required"
versionRange="[${syrupLibraryVersion},)"
ordering="AFTER"
side="BOTH"
